### ISSUE TITLE
FIrebase - Mapbox

### ISSUE THREAD

**Issue by Stevesmith28** [CvmiloM/TeLlevoAPP#1]
export const environment = {
  production: true,
  firebaseConfig: {
    apiKey: "",
    authDomain: "t",
    projectId: "",
    storageBucket: " ",
    messagingSenderId: "",
    appId: ":"
  },
  accessToken: ' '
};

Como tienes configurado el firebase, y el mapbox? al ejecutar la app me causa error, he creado proyecto en firebase rellenando esta parte, y tambien en mapbox pero no se muestra correctamente, me podrias ayudar :)

**Comment by CvmiloM** [comment]
Hola viejo mira en esa apartado de  environment tienes que colocar tus
tokens tanto de fire base y de mapbox no se si ya rellenante eso y el tema
es que tienes que tener tanto activada como el tema de autenticacion / el
realtime database / storage algo asi tengo el real time database para que
tengas una idea y con el tema del mapbox no tienes que configurar nada ya
que solo necesitas el token que te da la cuenta
[image: image.png]

**Comment by Stevesmith28** [comment]
okey, tendrás alguna wiki en tu proyecto como configurar eso?

**Comment by CvmiloM** [comment]
te cree una wiki para que veas como es el tema si tienes alguna duda escríbeme  
![image](https://github.com/user-attachments/assets/4c88ac38-6257-4809-8238-eb4fb98e9129)

**Comment by Stevesmith28** [comment]
como te contacto, tienes discord? he configurado todo correctamente como lo escribiste en tu wiki, pero me da error.

**Comment by CvmiloM** [comment]
mira búscame como tamilo en ds

**Comment by Stevesmith28** [comment]
te envié solicitud

**Comment by Stevesmith28** [comment]
he visto nuevos cambios, esta genial, pero tengo duda porque la funcion que esta definida de reenviar a /home,  cuando abres la app estas en /sign-up  ingresas tus datos y te registras no te reenvia hacia /home , y lo otro cuando desactivas internet cierro la app, puedo entrar bien pero no me aparecen los viajes ,si yo fuera pasajero y perdiera conexion como le demuestro al conductor que tomé su viaje
